[tools]
node = "20"

[env]
# DEBUG = "true"  # 必要なら

[tasks.setup]
description = "初期セットアップ"
run = "npm install"

[tasks.typecheck]
description = "TypeScript型チェック"
run = "npx tsc --noEmit"

[tasks.vercel-build]
description = "Vercelビルド"
run = "vercel build"

[tasks.clean]
description = "キャッシュ・storybook静的ファイル削除"
run = "rm -rf node_modules/.cache storybook-static"

[tasks.storybook]
description = "Storybook起動"
run = "npm run storybook"
