rules:
  - id: no-console-error-in-production
    pattern: console.error(...)
    message: |
      console.error() should not be used in production code. 
      Use secure logging mechanism instead.
    languages: [typescript, javascript]
    severity: WARNING
    paths:
      include:
        - "src/**/*.ts"
        - "src/**/*.tsx"
      exclude:
        - "**/*.test.*"
        - "**/*.stories.*"
        - "**/*.dev.*"

  - id: secure-env-var-check
    pattern-either:
      - pattern: process.env.$VAR
    message: |
      Environment variable access detected. Ensure proper validation 
      and error handling for undefined values.
    languages: [typescript, javascript]
    severity: INFO
    paths:
      include:
        - "src/**/*.ts"
        - "src/**/*.tsx"
    
  - id: api-token-in-client-code
    pattern-either:
      - pattern: |
          process.env.FIGMA_ACCESS_TOKEN
      - pattern: |
          process.env.FIGMA_PERSONAL_ACCESS_TOKEN
    message: |
      API tokens should only be used in server-side code. 
      Ensure this code runs on the server.
    languages: [typescript, javascript]
    severity: ERROR
    paths:
      include:
        - "src/**/*.ts"
        - "src/**/*.tsx"
      exclude:
        - "src/pages/api/**"
        - "src/app/api/**"
        - "src/lib/**"  # Exclude server-side library code
        - "scripts/**"  # Exclude build/deployment scripts

  - id: localStorage-security-check
    pattern-either:
      - pattern: localStorage.setItem($KEY, $VALUE)
      - pattern: sessionStorage.setItem($KEY, $VALUE)
    message: |
      Storing sensitive data in localStorage/sessionStorage can be risky.
      Ensure data is properly encrypted and validated.
    languages: [typescript, javascript]
    severity: WARNING
    paths:
      include:
        - "src/**/*.ts"
        - "src/**/*.tsx"

  - id: weak-crypto-detection
    pattern-either:
      - pattern: Math.random()
      - pattern: Date.now()
    message: |
      Weak randomness detected. Use crypto.randomBytes() or crypto.getRandomValues() 
      for security-sensitive operations.
    languages: [typescript, javascript]
    severity: WARNING
    paths:
      include:
        - "src/**/*.ts"
        - "src/**/*.tsx"
      exclude:
        - "**/*.test.*"
        - "**/*.stories.*"

  - id: sql-injection-risk
    pattern-either:
      - pattern: |
          $SQL + $VAR
      - pattern: |
          `$SQL${$VAR}`
    message: |
      Potential SQL injection risk. Use parameterized queries or prepared statements.
    languages: [typescript, javascript]
    severity: ERROR
    paths:
      include:
        - "src/**/*.ts"
        - "src/**/*.tsx"
